# =============================================
# PERFIL PRODUCCIÓN
# =============================================

# =============================================
# CONFIGURACIÓN SERVIDOR
# =============================================
server.port=${SERVER_PORT:8080}

# =============================================
# CONFIGURACIÓN BASE DE DATOS PRODUCCIÓN (MariaDB)
# =============================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# =============================================
# CONFIGURACIÓN LOGS
# =============================================
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.com.padelzgz=INFO